import { Geist, Geist_Mono, Lato } from 'next/font/google';

import './globals.css';
import type { Metadata } from 'next';

import GlobalLayout from './cv/_components/GlobalLayout';

import ReactQueryClientProvider from '@/providers/ReactQueryClientProvider';
import { StoreProvider } from '@/providers/StoreProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={` ${lato.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryClientProvider>
          <StoreProvider>
            <GlobalLayout>{children}</GlobalLayout>
          </StoreProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
