import { Geist, Geist_Mono, Lato, Source_Sans_3 } from 'next/font/google';

import './globals.css';
import type { Metadata } from 'next';

import ReactQueryClientProvider from '@/providers/ReactQueryClientProvider';
import { StoreProvider } from '@/providers/StoreProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const lata = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const sourceSans = Source_Sans_3({
  variable: '--font-source-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${sourceSans.variable} ${lata.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <StoreProvider>{children}</StoreProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
